### ISSUE TITLE
unable to use input.txt for inputting the file

### ISSUE THREAD

**Issue by sreejithmm** [AkhilRautela/Competitive-Coding-Helpful-Script-for-VScode-#1]
`
sys.stdin, sys.stdout = IOWrapper(sys.stdin), IOWrapper(sys.stdout)
print(input)
input = lambda: sys.stdin.readline().rstrip("\r\n")
print(input)

print("hello world")
val = input()
print(val)

print("Goodye world")
`
<img width="1440" alt="Screenshot 2021-06-10 at 10 43 05 AM" src="https://user-images.githubusercontent.com/9019968/121468667-cfb81a00-c9d8-11eb-822c-06521d0cec4b.png">

**Comment by AkhilRautela** [comment]
use the same template in python file as provided input.txt and output.txt should be at the root level
